#### create user
POST "localhost:3000/api/users"

{
  "username": "avarile",
  "email": "avarile@gmail.com",
  "password": "000000",
  "activated": false,
  "avatar": "admin"
  address: '84-88, south Melbourne';
  verified: 'false';
  phoneNumber: '0412345678';
  organization: 'AGI';
  desc: 'A fullstack programmer with strong Supplychain background.';
}